import type { Metadata } from 'next';

import Link from 'next/link';
import { Suspense } from 'react';
import { TranslationHistory } from './_components/TranslationHistory';
import { TranslationProvider } from './_contexts/TranslationContext';

import { Inter, Noto_Sans_JP } from 'next/font/google';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${inter.variable} ${notoSansJP.variable} font-sans antialiased`}>
        <TranslationProvider>
          <div className="flex h-screen">
            {/* Left Sidebar */}
            <div className="w-80 flex-shrink-0 flex flex-col border-r border-gray-200">
              {/* Logo/Icon */}
              <div className="p-4 flex-shrink-0">
                <Link
                  href="/"
                  className="flex items-center justify-center w-12 h-12 bg-blue-500 rounded-2xl hover:bg-blue-600 transition-colors"
                >
                  <span className="text-2xl">👀</span>
                </Link>
              </div>

              {/* History Section */}
              <div className="flex-1 overflow-hidden">
                <Suspense
                  fallback={
                    <div className="h-full flex items-center justify-center">Loading...</div>
                  }
                >
                  <TranslationHistory />
                </Suspense>
              </div>
            </div>

            {/* Main Content */}
            <div className="flex-1 flex flex-col items-center justify-center p-8 bg-blue-50">
              {children}
            </div>
          </div>
        </TranslationProvider>
      </body>
    </html>
  );
}
